# Generated by Django 5.2.17 on 2026-09-28 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animelist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
