# Generated by Django 5.2.17 on 2026-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animelist", "0003_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="comment",
            new_name="content",
        ),
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
            preserve_default=False,
        ),
    ]
