# Generated by Django 5.2.17 on 2026-09-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animelist", "0004_rename_comment_feedback_content_feedback_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="anime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animelist.anime",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
